/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
      },
    },
  },
  plugins: [],
  safelist: [
    // Força TODAS as classes que usamos no dashboard
    'bg-gradient-to-br',
    'from-blue-950',
    'via-blue-900',
    'to-indigo-950',
    'from-green-950',
    'to-green-900',
    'from-red-950',
    'to-red-900',
    'from-teal-950',
    'to-teal-900',
    'from-purple-950',
    'to-purple-900',
    'from-orange-950',
    'to-orange-900',
    'border-blue-800/50',
    'border-green-800/50',
    'border-red-800/50',
    'border-teal-800/50',
    'border-purple-800/50',
    'border-orange-800/50',
    'shadow-2xl',
    'hover:shadow-blue-900/50',
    'hover:shadow-green-600/30',
    'hover:shadow-red-600/30',
    'hover:shadow-teal-600/30',
    'hover:shadow-purple-600/30',
    'hover:shadow-orange-600/30',
    'text-blue-300',
    'text-green-300',
    'text-red-300',
    'text-teal-300',
    'text-purple-300',
    'text-orange-300',
    'aspect-square',
    'w-full',
    'lg:w-1/3',
    'lg:w-2/3',
    'grid-cols-1',
    'sm:grid-cols-2',
    'lg:grid-cols-4',
    'gap-6',
    'gap-8',
    'p-6',
    'p-8',
    'p-12',
    'rounded-3xl',
    'text-center',
    'flex',
    'flex-col',
    'justify-between',
    'justify-center',
    'flex-wrap',
    'transition-all',
  ],
}